# 오디오 설정
mute=yes
volume = 30

# 스크린샷 형식
screenshot-format=png

# 스크린샷 저장 디렉토리 (원하는 경로로 변경)
screenshot-dir=~/Downloads/mpv

# OSD 바를 표시하지 않습니다.
no-osd-bar
osd-level=2

# OSD 상태 메시지의 내용을 설정합니다.
profile=high-quality

