github.com:
    users:
        algento:
            oauth_token: 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
    git_protocol: https
    user: algento
    oauth_token: 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
