# <leader>, r: reload configuration
unbind r
bind r source-file ~/.tmux.conf

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g default-command "/bin/zsh"
set -g prefix C-s
set -g mouse on
set -g status-interval 5
set -g base-index 1

# Window and Pane nubmer
# - Start windows and panes index at 1, not 0
setw -g pane-base-index 1
set-option -g status-position top
# Ensure window index numbers get reordered on delete
set-option -g renumber-windows on
# set-environment -g TMUX_PLUGIN_MANAGER_PATH "${HOME}/.tmux/plugins/"

# act like vim
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'jimeh/tmuxifier'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

# Set catppuccin/tmux
run '~/.tmux/plugins/tmux/catppuccin.tmux'
set -g @catppuccin_flavor "mocha"

# set -g @catppuccin_status_fill "icon"
# set -g @catppuccin_window_status_enable "yes"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_date_time_text "%Y-%m-%d %H:%M"
# set -g @catppuccin_directory_text "#{pane_current_path}"

set -g status-left-length 100
set -g status-right-length 100
set -g status-left "#{E:@catppuccin_status_session}"

# set -g @catppuccin_status_modules_right "directory session"
set -g status-right "#{E:@catppuccin_status_directory}"
set -agF status-right "#{E:@catppuccin_status_date_time}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{ram_bg_color}  #[fg=#{@thm_fg},bg=#{@thm_bg}] #{ram_percentage} "
# set -ag status-right "#[fg=#{@thm_bg}]#{gpu_bg_color}   #[fg=#{@thm_fg},bg=#{@thm_bg}] #{gpu_percentage}"
# set -ag status-right "#[fg=#{cpu_fg_color},bg=#{cpu_bg_color}]   #{cpu_percentage}"
# set -agF status-right "#{E:@catppuccin_status_load} #{E:@catppuccin_status_host} #{E:@catppuccin_status_user}""

# Initialize tmux plugin manager (this line shold be at very bottom of file)
run '~/.tmux/plugins/tpm/tpm'
set -g status-style bg=default
